FROM mcr.microsoft.com/mssql/server:2017-latest-ubuntu  
WORKDIR /var/opt/sqlserver
ENV SA_PASSWORD=123456Ltl. \
	ACCEPT_EULA=Y  \
    MSSQL_PID=Express \
    MSSQL_BACKUP_DIR="/var/opt/sqlserver"  \
    MSSQL_DATA_DIR="/var/opt/sqlserver"  \ 
    MSSQL_LOG_DIR="/var/opt/sqlserver" 
EXPOSE 1433
