version: "3.3"

services: 
  db:
    build:
        context: .
        dockerfile: ./DockerFiles/Sql/DockerFile
    volumes:
       - ./DbData:/var/opt/sqlserver
    ports:
        - "1439:1433"
  api:
    build: 
      context: ../
      dockerfile: ./PortfolioDb/DockerFiles/Runtime/DockerFile
    ports: 
        - "5005:80"
    depends_on:
        - db
        - dbupdate
  dbupdate:
    build: 
      context: ../
      dockerfile: ./PortfolioDb/DockerFiles/CreateDb/DockerFile
    depends_on:
        - db



    
